[build]
  command = "npm run build && cd netlify/functions && npm install"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.18.2"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
